services:
  geant4:
    container_name: geant4
    build:
      dockerfile: ./Dockerfile
    volumes: 
      - /run/desktop/mnt/host/wslg/.X11-unix:/tmp/.X11-unix
      - /run/desktop/mnt/host/wslg:/mnt/wslg
      - geant4_data:/geant4_data
    environment:
      - DISPLAY=:0
      - WAYLAND_DISPLAY=wayland-0
      - XDG_RUNTIME_DIR=/mnt/wslg/runtime-dir
      - PULSE_SERVER=/mnt/wslg/PulseServer
volumes:
  geant4_data:
    labels:
      persistent: true
